run:
	@cargo r

build:
	@cargo b

clean:
	@rm -rf target

test:
	@cargo t

help:
	@echo "Usage: make [target]"
	@echo "  build      Build the application"
	@echo "  run        Run the application"
	@echo "  test       Run all tests"
	@echo "  clean      Clean up build artifacts"
